### ISSUE TITLE
iOS - Connect function crashes the app

### ISSUE THREAD

**Issue by nikolip** [alternadom/WiFiFlutter#211]
iOS - 15.2
-- 
wifi_iot: ^0.3.10
--

When calling WifiForIoTPlugin.connect the app crashes to null error. 

Only mandatory argument should be 'ssid', but when not providing "password" or "security" arguments the app crashes to "Could not cast value of type 'NSNull' (0x1dae296c0) to 'NSString' (0x1dae28b18).". 

When debugging with xcode those values comes to connect function as nil. Then when  plugin trying access  them in SwiftWifiIotPlugin  class in lines 126-128 if the value is nil the app crashes.

**Comment by daadu** [comment]
Working on its fix. Thanks for reporting.

**Comment by daadu** [comment]
The PR is under review - meanwhile urge you to test it with following:

```yaml
  wifi_iot: #^0.3.0
    git:
      url: https://github.com/daadu/WiFiFlutter
      path: packages/wifi_iot
      ref: fix-211
```

**Comment by daadu** [comment]
Fix released on pub with [v0.3.12](https://pub.dev/packages/wifi_iot/versions/0.3.12). Thanks again for @nikolip for reporting this bug, check yourself in README!

**Comment by nikolip** [comment]
Hey!

Sorry for not responding earlier.
When looking the pr - it seems like you have fixed the problem only when not providing security argument. (That works now)
But there is still the issue when you try to join an open wifi (no password needed).
eg.

WiFiForIoTPlugin.connect("wifi-ssid");

App still crashes then on SwiftWifiIotPlugin.swift line 126 when accessing call aguments.
let sPassword = (call.arguments as? [String : AnyObject])?["password"] as! String?

**Comment by daadu** [comment]
@DominikStarke can you look into it? If you got time.

**Comment by nikolip** [comment]
Any updates on this? @daadu

**Comment by daadu** [comment]
I couldn't work on it this weekend, probably next weekend.

Feel free to file PR if you know the solution.

**Comment by nikolip** [comment]
https://github.com/flutternetwork/WiFiFlutter/pull/224 @daadu
